<Project>
  <PropertyGroup>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>v1.1.0</InformationalVersion>
    <Company>RemoteMonitor</Company>
    <Product>Remote Monitor</Product>
  </PropertyGroup>
</Project>
