<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableStatusPushPrototype>true</EnableStatusPushPrototype>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\RemoteMonitor.Client\RemoteMonitor.Client.csproj"
                      AdditionalProperties="EnableStatusPushPrototype=true" />
    <ProjectReference Include="..\..\..\RemoteMonitor.Server\RemoteMonitor.Server.csproj"
                      AdditionalProperties="EnableStatusPushPrototype=true" />
  </ItemGroup>

</Project>
